import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI tutor",
  description: "Generated by create next app",
};


const clearAppearance = {
  variables: {
    colorPrimary: "#22c55e",
    colorText: "#ffffff",
    colorBackground: "#1d1f2b",
    colorInputBackground: "#2a2d3c",
    colorInputText: "#ffffff",
    colorBorder: "#ffffff",
  },
  elements:
  {
    card: "bg-[#1d1f2b] shadow-lg border border-gray-700",
    headerTitle: "text-white",
    headerSubtitle: "text-gray-300",
    formButtonPrimary: "bg-green-800 hover:bg-green-700 text-white",
    formFieldInput: "bg-[#2a2d3c] text-white border border-gray-600 focus:border-green-500 focus:ring-green-500",
    socialButtonsBlockButton: "bg-green-600 hover:bg-green-700 text-white",
    socialButtonsProviderIcon_google: "brightness-0 invert",
  }
}

export default function RootLayout({ children }) {
  return (
   
    <ClerkProvider  appearance={clearAppearance}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Provider>
          {children}   
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}










